// Introductory meanings for the Level 1 content library, not exhaustive dictionary senses.
// These are vocabulary entries, not scored practice questions or tagged sentence records.
export const LEVEL_ONE_CONTENT = {
  title: 'Pepeha',
  outcome: 'Say your pepeha.',
  vocabulary: [
    {
      title: 'Tūrangawaewae', focus: 'Where you’re from and the places you belong.',
      sources: [
        { label: 'NZ History', url: 'https://nzhistory.govt.nz/culture/maori-language-week/365-maori-words' },
        { label: 'Te Aka', url: 'https://maoridictionary.co.nz/search?keywords=k%C4%81inga' },
      ],
      words: [
        { label: 'tūrangawaewae', meaning: 'A place of belonging; a place to stand' },
        { label: 'whenua', meaning: 'Land; homeland' },
        { label: 'maunga', meaning: 'Mountain' },
        { label: 'awa', meaning: 'River' },
        { label: 'moana', meaning: 'Sea; ocean; large lake' },
        { label: 'roto', meaning: 'Lake' },
        { label: 'rohe', meaning: 'Territory; district; region' },
        { label: 'iwi', meaning: 'Tribe; people' },
        { label: 'hapū', meaning: 'Kinship group; subtribe' },
        { label: 'marae', meaning: 'Marae; communal meeting complex' },
        { label: 'waka', meaning: 'Canoe; boat' },
        { label: 'kāinga', meaning: 'Home; settlement' },
      ],
    },
    {
      title: 'Whānau', focus: 'Family members and relationships.',
      sources: [
        { label: 'Kupu', url: 'https://kupu.maori.nz/set/Family' },
        { label: 'Te Aka: tuākana', url: 'https://maoridictionary.co.nz/search?idiom=&keywords=cousin&loan=&phrase=&proverb=' },
        { label: 'NZ History', url: 'https://nzhistory.govt.nz/culture/maori-language-week/365-maori-words' },
      ],
      words: [
        { label: 'whānau', meaning: 'Family; extended family' },
        { label: 'whaea', meaning: 'Mother; aunt' },
        { label: 'pāpā', meaning: 'Father; dad' },
        { label: 'matua', meaning: 'Parent; father' },
        { label: 'mātua', meaning: 'Parents' },
        { label: 'tama', meaning: 'Son; boy' },
        { label: 'tamāhine', meaning: 'Daughter' },
        { label: 'tamaiti', meaning: 'Child' },
        { label: 'tamariki', meaning: 'Children' },
        { label: 'tuakana', meaning: 'Older sibling of the same gender' },
        { label: 'tuākana', meaning: 'Older siblings of the same gender (plural)' },
        { label: 'teina', meaning: 'Younger sibling of the same gender' },
        { label: 'tungāne', meaning: 'Brother of a female' },
        { label: 'tuahine', meaning: 'Sister of a male' },
        { label: 'koroua', meaning: 'Grandfather; elderly man' },
        { label: 'kuia', meaning: 'Grandmother; elderly woman' },
        { label: 'mokopuna', meaning: 'Grandchild' },
        { label: 'whakapapa', meaning: 'Genealogy; family connections' },
      ],
    },
    {
      title: 'Mahi', focus: 'Corporate and public-sector roles for Ministry of Education and government teams.',
      sources: [
        { label: 'Public-sector job titles', url: 'https://www.desc.govt.nz/assets/Uploads/DocumentLibrary/OIA-2023-4882_Use-of-te-Reo-Maori-.pdf' },
        { label: 'Fire and Emergency NZ', url: 'https://portal.fireandemergency.nz/national-teams/kaupapa-maori-and-cultural-communities/te-reo-maori/job-titles-in-te-reo-maori/' },
        { label: 'Ministry of Education', url: 'https://careers.education.govt.nz/learning-support-roles/' },
        { label: 'Kupu: manager', url: 'https://kupu.maori.nz/set/My-Occupation' },
      ],
      words: [
        { label: 'kaitohutohu', meaning: 'Advisor' },
        { label: 'kaitohutohu matua', meaning: 'Senior advisor' },
        { label: 'kaitohutohu mātāmua', meaning: 'Principal advisor; chief advisor' },
        { label: 'kaitohutohu ārahi', meaning: 'Lead advisor' },
        { label: 'kaitātari', meaning: 'Analyst' },
        { label: 'kaitātari kaupapahere', meaning: 'Policy analyst' },
        { label: 'kaitātari matua kaupapahere', meaning: 'Senior policy analyst' },
        { label: 'kaitātari mātāmua kaupapahere', meaning: 'Principal policy analyst' },
        { label: 'kaitātari pakihi', meaning: 'Business analyst' },
        { label: 'kaiwhakahaere', meaning: 'Manager' },
        { label: 'kaiwhakahaere ratonga pakihi', meaning: 'Business services manager' },
        { label: 'kairuruku ratonga pakihi', meaning: 'Business services coordinator' },
        { label: 'āpiha whakarite', meaning: 'Administration officer' },
        { label: 'kaiāwhina whakarite', meaning: 'Administration assistant' },
        { label: 'kaitautoko whakarite', meaning: 'Administration support' },
        { label: 'kaikaute', meaning: 'Accountant' },
        { label: 'āpiha pūtea', meaning: 'Finance officer' },
        { label: 'kaitohutohu whiwhinga', meaning: 'Procurement advisor' },
        { label: 'kaiarotake', meaning: 'Auditor' },
        { label: 'kaitohutohu mātauranga', meaning: 'Learning support advisor' },
      ],
      note: 'Job titles vary between agencies. Use your organisation’s approved title when introducing yourself.',
    },
  ],
} as const
