import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createHmac} from 'node:crypto'
import {authorizedInvitationSend,invitationMessage,deliverInvitation} from './invitation-mail.mjs'
const id='12345678-1234-1234-1234-123456789012',row={invitation_id:id,recipient:'student@example.com',subject:'Kia ora Māori',text:'Personal text',html:'<p>Personal text</p>'}
test('requires scoped, fresh signature',()=>{const timestamp=String(Date.now()),signature=createHmac('sha256','secret').update(`invitation-send:${timestamp}:${id}`).digest('hex'),h={'x-send-timestamp':timestamp,'x-send-signature':signature};assert(authorizedInvitationSend(h,id,'secret'));assert(!authorizedInvitationSend(h,id,'wrong'));assert(!authorizedInvitationSend(h,id,'secret',Date.now()+400000));assert(!authorizedInvitationSend(h,'other','secret'))})
test('one recipient, multipart content, injection rejected',()=>{const s=Buffer.from(invitationMessage(row),'base64url').toString();assert(s.includes('To: student@example.com\r\n'));assert(s.includes('multipart/alternative'));assert(!s.includes('Bcc:'));assert.throws(()=>invitationMessage({...row,recipient:'a@example.com\r\nBcc: x@example.com'}))})
test('atomic claim prevents repeated sending',async()=>{let claimed=false,sends=0;const query=async sql=>({rows:sql.startsWith('update public.kp_invitation_mail m')&&!claimed?(claimed=true,[row]):[]});const opts={getToken:async()=> 'test',send:async()=>{sends++;return {ok:true,json:async()=>({id:'receipt'})}}};assert.equal((await deliverInvitation(query,id,opts)).status,'sent');assert.equal((await deliverInvitation(query,id,opts)).status,'not_claimed');assert.equal(sends,1)})
test('ambiguous failure is held for review',async()=>{let held=false;const query=async sql=>{if(sql.includes("status='uncertain'"))held=true;return {rows:sql.includes('returning m.*')?[row]:[]}};assert.equal((await deliverInvitation(query,id,{getToken:async()=> 'test',send:async()=>{throw Error('timeout')}})).status,'uncertain');assert(held)})
