// Stable question IDs preserve existing chat and personal answers as the lesson grows.
export const bigWordQuestions = [
  { id: 0, group: 'Ko', text: 'Ko wai tō matua?' },
  { id: 1, group: 'Ko', text: 'Ko wai tō whaea?' },
  { id: 2, group: 'Nō', text: 'Nō hea tō matua?' },
  { id: 3, group: 'Nō', text: 'Nō hea tō whaea?' },
  { id: 4, group: 'He', text: 'He aha tō matua?' },
  { id: 5, group: 'He', text: 'He aha tō whaea?' },
  { id: 6, group: 'Kei', text: 'Kei hea tō matua?' },
  { id: 7, group: 'Kei', text: 'Kei hea tō whaea?' },
  { id: 8, group: 'Toko-', text: 'Tokohia ō tamariki?' },
  { id: 9, group: 'E', text: 'E hia ngā rā o te wiki?' },
  { id: 10, group: 'Ko', text: 'Ko wai tō tino mema o te rōpū The Beatles?' },
  { id: 11, group: 'Ko', text: 'Ko wai tō tino kaiwaiata?' },
  { id: 12, group: 'Nō', text: 'Nō hea a Freddie Mercury?' },
  { id: 13, group: 'Nō', text: 'Nō hea koe?' },
  { id: 14, group: 'He', text: 'He aha tō mahi?' },
  { id: 15, group: 'He', text: 'He aha tō tino kai?' },
  { id: 16, group: 'Kei', text: 'Kei hea koe?' },
  { id: 17, group: 'Kei', text: 'Kei hea tō waea?' },
  { id: 18, group: 'E', text: 'E hia ngā marama o te tau?' },
  { id: 19, group: 'E', text: 'E hia ngā wira o te motokā?' },
  { id: 20, group: 'Toko-', text: 'Tokohia ngā mema o The Beatles?' },
  { id: 21, group: 'Toko-', text: 'Tokohia ngā tāngata i tō whānau?' },
  { id: 22, group: 'Kotahi', text: 'Kotahi tō waea?' },
  { id: 23, group: 'Kotahi', text: 'Kotahi tō mōkai?' },
  { id: 24, group: 'Kotahi', text: 'Kotahi te rā o te wiki?' },
  { id: 25, group: 'Kāorekau', text: 'Kāorekau ō mōkai?' },
  { id: 26, group: 'Kāorekau', text: 'Kāorekau ō tamariki?' },
  { id: 27, group: 'Kāorekau', text: 'Kāorekau he wira o te motokā?' },
] as const
export const bigWordQuestionGroups = ['Ko', 'Nō', 'He', 'Kei', 'E', 'Toko-', 'Kotahi', 'Kāorekau'] as const
